# ============================================================
# Fitmanaged.com - Alias Migration to M365
# Run from Exchange Online PowerShell
# ============================================================

# Connect-ExchangeOnline -UserPrincipalName admin@fitmanaged.com

# ============================================================
# INFO@fitmanaged.com Aliases
# ============================================================

$infoAliases = @(
    "smtp:3creek@fitmanaged.com"
    "smtp:3creek2@fitmanaged.com"
    "smtp:3creek3@fitmanaged.com"
    "smtp:agpc@fitmanaged.com"
    "smtp:alerts@fitmanaged.com"
    "smtp:altitude@fitmanaged.com"
    "smtp:altitudelive1@fitmanaged.com"
    "smtp:annframe@fitmanaged.com"
    "smtp:ariddell@fitmanaged.com"
    "smtp:aspentravel@fitmanaged.com"
    "smtp:aspentravel2@fitmanaged.com"
    "smtp:axisgymnastics@fitmanaged.com"
    "smtp:barkerewing@fitmanaged.com"
    "smtp:bates@fitmanaged.com"
    "smtp:bearcreek@fitmanaged.com"
    "smtp:beddow@fitmanaged.com"
    "smtp:belarc@fitmanaged.com"
    "smtp:bellecose@fitmanaged.com"
    "smtp:bellecoselive1@fitmanaged.com"
    "smtp:bellecosemozy1@fitmanaged.com"
    "smtp:berlin@fitmanaged.com"
    "smtp:bigr@fitmanaged.com"
    "smtp:bigradmin@fitmanaged.com"
    "smtp:boothcreek@fitmanaged.com"
    "smtp:brainhealth@fitmanaged.com"
    "smtp:bridgercare@fitmanaged.com"
    "smtp:caldera@fitmanaged.com"
    "smtp:caldera2@fitmanaged.com"
    "smtp:caldera3@fitmanaged.com"
    "smtp:caldera4@fitmanaged.com"
    "smtp:calderamrtech2@fitmanaged.com"
    "smtp:calderamrtech3@fitmanaged.com"
    "smtp:campbell@fitmanaged.com"
    "smtp:carney@fitmanaged.com"
    "smtp:cbarv@fitmanaged.com"
    "smtp:cdietzmann@fitmanaged.com"
    "smtp:cdm@fitmanaged.com"
    "smtp:cfjh@fitmanaged.com"
    "smtp:cfjh2@fitmanaged.com"
    "smtp:cfjh3@fitmanaged.com"
    "smtp:cfjh4@fitmanaged.com"
    "smtp:cfta@fitmanaged.com"
    "smtp:cftv@fitmanaged.com"
    "smtp:childress@fitmanaged.com"
    "smtp:choiburns@fitmanaged.com"
    "smtp:citypass@fitmanaged.com"
    "smtp:clc@fitmanaged.com"
    "smtp:cloudsrv@fitmanaged.com"
    "smtp:colemanandrews@fitmanaged.com"
    "smtp:conservationfund@fitmanaged.com"
    "smtp:corelytics@fitmanaged.com"
    "smtp:cowboy@fitmanaged.com"
    "smtp:cribiore@fitmanaged.com"
    "smtp:crystalcreek@fitmanaged.com"
    "smtp:crystalcreeklive1@fitmanaged.com"
    "smtp:crystalsprings@fitmanaged.com"
    "smtp:crystalspringslive1@fitmanaged.com"
    "smtp:crystalspringslive2@fitmanaged.com"
    "smtp:csamjh@fitmanaged.com"
    "smtp:csf@fitmanaged.com"
    "smtp:csr@fitmanaged.com"
    "smtp:ddx@fitmanaged.com"
    "smtp:ddx2@fitmanaged.com"
    "smtp:defazio@fitmanaged.com"
    "smtp:defaziolaw@fitmanaged.com"
    "smtp:dellorders@fitmanaged.com"
    "smtp:dlo@fitmanaged.com"
    "smtp:domains@fitmanaged.com"
    "smtp:dynia@fitmanaged.com"
    "smtp:dynia2@fitmanaged.com"
    "smtp:dynia3@fitmanaged.com"
    "smtp:dynialive1@fitmanaged.com"
    "smtp:edwigg@fitmanaged.com"
    "smtp:epsilon@fitmanaged.com"
    "smtp:epsilon3@fitmanaged.com"
    "smtp:epsilon4@fitmanaged.com"
    "smtp:fax@fitmanaged.com"
    "smtp:fit@fitmanaged.com"
    "smtp:gallatin@fitmanaged.com"
    "smtp:gallatin2@fitmanaged.com"
    "smtp:gallatin3@fitmanaged.com"
    "smtp:glsllp@fitmanaged.com"
    "smtp:google@fitmanaged.com"
    "smtp:gvrr@fitmanaged.com"
    "smtp:halpin@fitmanaged.com"
    "smtp:hbd@fitmanaged.com"
    "smtp:hershberger@fitmanaged.com"
    "smtp:hershberger1@fitmanaged.com"
    "smtp:highfive@fitmanaged.com"
    "smtp:inanyevent@fitmanaged.com"
    "smtp:insurancesolutions@fitmanaged.com"
    "smtp:ja@fitmanaged.com"
    "smtp:jalive1@fitmanaged.com"
    "smtp:jalive12@fitmanaged.com"
    "smtp:jalive2@fitmanaged.com"
    "smtp:jalive5@fitmanaged.com"
    "smtp:jalive6@fitmanaged.com"
    "smtp:jalive8@fitmanaged.com"
    "smtp:jalive9@fitmanaged.com"
    "smtp:jaoffice@fitmanaged.com"
    "smtp:ja_live4@fitmanaged.com"
    "smtp:jhcs@fitmanaged.com"
    "smtp:jhlt@fitmanaged.com"
    "smtp:jhltvl@fitmanaged.com"
    "smtp:jhmpaccounting@fitmanaged.com"
    "smtp:jorgensen@fitmanaged.com"
    "smtp:jorgensen2@fitmanaged.com"
    "smtp:jsf@fitmanaged.com"
    "smtp:karla@fitmanaged.com"
    "smtp:lcr@fitmanaged.com"
    "smtp:leavellcpa@fitmanaged.com"
    "smtp:leavelllive1@fitmanaged.com"
    "smtp:leavelllive2@fitmanaged.com"
    "smtp:lmi@fitmanaged.com"
    "smtp:lostcreek@fitmanaged.com"
    "smtp:lukas@fitmanaged.com"
    "smtp:meridian@fitmanaged.com"
    "smtp:meridianlive1@fitmanaged.com"
    "smtp:mixter@fitmanaged.com"
    "smtp:mlslawyers@fitmanaged.com"
    "smtp:mlslawyers2@fitmanaged.com"
    "smtp:mountainkhakis@fitmanaged.com"
    "smtp:mowens@fitmanaged.com"
    "smtp:mspf@fitmanaged.com"
    "smtp:mtnhigh@fitmanaged.com"
    "smtp:nmwa@fitmanaged.com"
    "smtp:nmwa2@fitmanaged.com"
    "smtp:nmwa3@fitmanaged.com"
    "smtp:nmwa4@fitmanaged.com"
    "smtp:osls@fitmanaged.com"
    "smtp:owen@fitmanaged.com"
    "smtp:parda@fitmanaged.com"
    "smtp:pdw@fitmanaged.com"
    "smtp:pierson@fitmanaged.com"
    "smtp:plw@fitmanaged.com"
    "smtp:plwlive@fitmanaged.com"
    "smtp:plwlive2@fitmanaged.com"
    "smtp:quosal@fitmanaged.com"
    "smtp:rainmakercoaching@fitmanaged.com"
    "smtp:rainmakerlandscaping@fitmanaged.com"
    "smtp:receipts@fitmanaged.com"
    "smtp:reinertres@fitmanaged.com"
    "smtp:rmc@fitmanaged.com"
    "smtp:rmclaptop@fitmanaged.com"
    "smtp:sands@fitmanaged.com"
    "smtp:scarlettcapital@fitmanaged.com"
    "smtp:sccd@fitmanaged.com"
    "smtp:scr@fitmanaged.com"
    "smtp:scrlive1@fitmanaged.com"
    "smtp:scrlive2@fitmanaged.com"
    "smtp:scrlive3@fitmanaged.com"
    "smtp:scrr@fitmanaged.com"
    "smtp:shootingstar@fitmanaged.com"
    "smtp:sis@fitmanaged.com"
    "smtp:sonicwall@fitmanaged.com"
    "smtp:ssjh@fitmanaged.com"
    "smtp:ssjh15@fitmanaged.com"
    "smtp:ssjh2016@fitmanaged.com"
    "smtp:ssjh2017@fitmanaged.com"
    "smtp:ssjh22@fitmanaged.com"
    "smtp:ssjhlive@fitmanaged.com"
    "smtp:ssjhlive1@fitmanaged.com"
    "smtp:ssjhlive2@fitmanaged.com"
    "smtp:storagecraftmsp@fitmanaged.com"
    "smtp:sundance@fitmanaged.com"
    "smtp:tcd@fitmanaged.com"
    "smtp:tcsar@fitmanaged.com"
    "smtp:tcsd@fitmanaged.com"
    "smtp:tetcon@fitmanaged.com"
    "smtp:tetonconservation@fitmanaged.com"
    "smtp:tetonlawyer@fitmanaged.com"
    "smtp:theoxbowgroup@fitmanaged.com"
    "smtp:tlc@fitmanaged.com"
    "smtp:tlc-ehs@fitmanaged.com"
    "smtp:tlcregionalloffice@fitmanaged.com"
    "smtp:tlpc@fitmanaged.com"
    "smtp:tlpc1@fitmanaged.com"
    "smtp:tls@fitmanaged.com"
    "smtp:tls3@fitmanaged.com"
    "smtp:tls4@fitmanaged.com"
    "smtp:tlsaccounting@fitmanaged.com"
    "smtp:tlsaccounting2@fitmanaged.com"
    "smtp:tlsaccounting3@fitmanaged.com"
    "smtp:toranaccounting@fitmanaged.com"
    "smtp:tributary@fitmanaged.com"
    "smtp:trlt@fitmanaged.com"
    "smtp:valleylumber@fitmanaged.com"
    "smtp:vla@fitmanaged.com"
    "smtp:vla1@fitmanaged.com"
    "smtp:vlalive1@fitmanaged.com"
    "smtp:vlr@fitmanaged.com"
    "smtp:waltonbu2@fitmanaged.com"
    "smtp:webrootapi@fitmanaged.com"
    "smtp:whc@fitmanaged.com"
    "smtp:willowstreet@fitmanaged.com"
    "smtp:womack@fitmanaged.com"
    "smtp:womack2@fitmanaged.com"
    "smtp:wort@fitmanaged.com"
    "smtp:worthotel@fitmanaged.com"
    "smtp:wortlive1@fitmanaged.com"
    "smtp:wortlive2@fitmanaged.com"
    "smtp:wortlive5@fitmanaged.com"
    "smtp:wsg@fitmanaged.com"
    "smtp:zach@fitmanaged.com"
)

Write-Host "Adding $($infoAliases.Count) aliases to info@fitmanaged.com..."
foreach ($alias in $infoAliases) {
    Set-Mailbox "info@fitmanaged.com" -EmailAddresses @{add=$alias}
    Write-Host "  Added: $alias"
}

# ============================================================
# PURCHASE@fitmanaged.com Aliases
# ============================================================

$purchaseAliases = @(
    "smtp:3creek@fitmanaged.com"
    "smtp:barkerewing@fitmanaged.com"
    "smtp:carriejhsc@fitmanaged.com"
    "smtp:domains@fitmanaged.com"
    "smtp:dynia4@fitmanaged.com"
    "smtp:epsilon2@fitmanaged.com"
    "smtp:hershberger2@fitmanaged.com"
    "smtp:hershberger3@fitmanaged.com"
    "smtp:jalive10@fitmanaged.com"
    "smtp:jalive11@fitmanaged.com"
    "smtp:jalive7@fitmanaged.com"
    "smtp:katharineconover@fitmanaged.com"
    "smtp:meg@fitmanaged.com"
    "smtp:montanafamilyplanning@fitmanaged.com"
    "smtp:osls@fitmanaged.com"
    "smtp:osls1@fitmanaged.com"
    "smtp:osls2@fitmanaged.com"
    "smtp:scarlett@fitmanaged.com"
    "smtp:springcreekranch@fitmanaged.com"
    "smtp:ssjh@fitmanaged.com"
    "smtp:ssjhcorp@fitmanaged.com"
    "smtp:ssjhlive3@fitmanaged.com"
    "smtp:ssjhlive4@fitmanaged.com"
    "smtp:stillwater@fitmanaged.com"
    "smtp:stillwest@fitmanaged.com"
    "smtp:tls-adobe@fitmanaged.com"
    "smtp:tls2@fitmanaged.com"
    "smtp:toolson@fitmanaged.com"
    "smtp:vla1@fitmanaged.com"
    "smtp:vlr@fitmanaged.com"
    "smtp:vpm@fitmanaged.com"
    "smtp:wortlive3@fitmanaged.com"
    "smtp:wortlive6@fitmanaged.com"
    "smtp:ww@fitmanaged.com"
)

Write-Host "Adding $($purchaseAliases.Count) aliases to purchase@fitmanaged.com..."
foreach ($alias in $purchaseAliases) {
    Set-Mailbox "purchase@fitmanaged.com" -EmailAddresses @{add=$alias}
    Write-Host "  Added: $alias"
}

Write-Host ""
Write-Host "Done! Summary:"
Write-Host "  info@fitmanaged.com    - aliases added"
Write-Host "  purchase@fitmanaged.com - aliases added"
Write-Host ""
Write-Host "NOTE: The following 7 aliases route to BOTH mailboxes in Rackspace."
Write-Host "In M365 you cannot add the same alias to two mailboxes."
Write-Host "Decide which mailbox should be primary, or create a Distribution Group for each:"
Write-Host "  3creek, barkerewing, domains, osls, ssjh, vla1, vlr"
